"""Generate the ``dialsbin`` forwarders for the DIALS dispatchers.

The installers deliberately expose only the DIALS/xia2/dxtbx/cctbx commands, so
that activating DIALS does not put the whole bundled conda environment on PATH.
The original post-install scripts did that by copying dispatchers out of
``bin``/``Scripts`` into ``dialsbin`` at install time.  Copies go stale as soon
as the underlying package is updated, and conda does not know about them, so
they are also left behind on uninstall.

Instead we enumerate the dispatchers at *build* time -- this recipe pins the
exact DIALS version it is built against -- and ship a forwarder per command.
Each forwarder:

  * locates its target relative to itself, so nothing needs the build prefix
    rewritten and the installation stays relocatable;
  * sets up the conda environment's PATH *for the child process only*.

That second point matters more than it looks.  ``dialsbin`` is the only thing
the user ever puts on PATH, but the programs themselves still need the real
environment: on Windows for DLL resolution, and on both platforms because DIALS
and xia2 spawn each other by bare command name (Windows ``CreateProcess`` only
searches PATH and only appends ``.exe``, so a bare ``dials.integrate`` has to
resolve to the real dispatcher in ``Scripts``).  A copied dispatcher cannot do
this; a forwarder can, without leaking anything into the user's shell.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

# Command families that make up the user-facing DIALS installation.
DISPATCHER_PREFIXES = ("dials", "xia2", "dxtbx", "cctbx")

# Directories conda's own activation prepends to PATH on Windows, in order.
# Applied inside each forwarder so the child process behaves exactly as it
# would in a fully activated environment.
WINDOWS_PATH_DIRS = (
    "",  # the prefix itself: python.exe and its DLLs
    r"\Library\mingw-w64\bin",
    r"\Library\usr\bin",
    r"\Library\bin",
    r"\Scripts",
    r"\bin",
)

# Extensions in Scripts/ that are directly executable, most preferred first.
WINDOWS_EXECUTABLE_SUFFIXES = (".exe", ".bat", ".cmd")

UNIX_SHIM = """\
#!/bin/sh
# Forwarder generated by dials-launcher. Do not edit.
prefix=$(cd -- "$(dirname -- "$0")/.." && pwd)
PATH="$prefix/bin:$PATH"
export PATH
exec "$prefix/bin/{target}" "$@"
"""

WINDOWS_SHIM = """\
@rem Forwarder generated by dials-launcher. Do not edit.
@setlocal EnableExtensions
@set "PREFIX=%~dp0.."
@set "PATH={path}%PATH%"
@{invoke}"%PREFIX%\\Scripts\\{target}" %*
"""


def unix_dispatchers(bindir: Path) -> list[str]:
    """Names of the dispatchers to forward to, from ``$PREFIX/bin``."""
    names = set()
    for prefix in DISPATCHER_PREFIXES:
        for path in bindir.glob(f"{prefix}*"):
            if path.is_file() and os.access(path, os.X_OK):
                names.add(path.name)
    return sorted(names)


def windows_dispatchers(scriptsdir: Path) -> dict[str, str]:
    """Map command name -> file to invoke, from ``%PREFIX%\\Scripts``.

    Console scripts appear as a ``name.exe``/``name-script.py`` pair; cctbx-style
    dispatchers may instead be plain ``name.bat``.  Both are keyed on the command
    name, preferring the ``.exe`` where a command has more than one form.
    """
    found: dict[str, str] = {}
    for prefix in DISPATCHER_PREFIXES:
        for path in scriptsdir.glob(f"{prefix}*"):
            if not path.is_file():
                continue
            suffix = path.suffix.lower()
            if suffix not in WINDOWS_EXECUTABLE_SUFFIXES:
                continue  # -script.py helpers, manifests, etc.
            command = path.stem
            existing = found.get(command)
            if existing is not None:
                rank = WINDOWS_EXECUTABLE_SUFFIXES.index
                if rank(Path(existing).suffix.lower()) <= rank(suffix):
                    continue
            found[command] = path.name
    return dict(sorted(found.items()))


def write_unix_shims(prefix: Path, outdir: Path) -> int:
    dispatchers = unix_dispatchers(prefix / "bin")
    for name in dispatchers:
        shim = outdir / name
        shim.write_text(UNIX_SHIM.format(target=name))
        shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return len(dispatchers)


def write_windows_shims(prefix: Path, outdir: Path) -> int:
    dispatchers = windows_dispatchers(prefix / "Scripts")
    path = "".join(f"%PREFIX%{d};" for d in WINDOWS_PATH_DIRS)
    for command, target in dispatchers.items():
        # A .bat target must be invoked with `call`, or control never returns
        # here and the exit code is lost.
        invoke = "call " if Path(target).suffix.lower() in (".bat", ".cmd") else ""
        shim = outdir / f"{command}.bat"
        shim.write_text(WINDOWS_SHIM.format(path=path, invoke=invoke, target=target))
    return len(dispatchers)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prefix", required=True, type=Path, help="build prefix")
    parser.add_argument("--platform", required=True, choices=("unix", "win"))
    args = parser.parse_args(argv)

    outdir = args.prefix / "dialsbin"
    outdir.mkdir(parents=True, exist_ok=True)

    if args.platform == "unix":
        count = write_unix_shims(args.prefix, outdir)
    else:
        count = write_windows_shims(args.prefix, outdir)

    if not count:
        # Silently shipping an empty dialsbin would produce an installer whose
        # setpaths puts an empty directory on PATH and nothing else.
        parser.error(f"no dispatchers found under {args.prefix} for {DISPATCHER_PREFIXES}")

    print(f"dials-launcher: generated {count} forwarders in {outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
